### PR TITLE
implement Live Radio Protocol and update CCSMB-5 metadata

### LINKED ISSUE #1: Live Radio Protocol support (LRP)
Example code: https://p.sc3.io/JR6XeAtBTc

If the message is a table and the table has the "song" key with DFPWM data, its LRP.

### LINKED ISSUE #2: CCSMB-5 metadata update
Support the updated metadata format that was released lately in CCSMB-5

### PR DESCRIPTION
**Pull request by WindClan**

### CODE REVIEW

**Comment by EmmaKnijn** [comment]
Could you add a comment describing the protocol

**Comment by WindClan** [comment]
> Could you add a comment describing the protocol

If a stream is a table and has a value named "song" that contains data, a "songname" value that contains the song's name, and a "songartist" value that contains the song's creator, it is most likely Live Radio Protocol

**Comment by EmmaKnijn** [comment]
In the code, that is

**Comment by WindClan** [comment]
The code checks if the message is a table and if it contains a value named "song"
The code decodes "song" using the decoder and pulls "songartist" and "songname" to fill in the "song name" and "artist name" sections on the GUI. The decoded data is then sent to the speaker, playing it

**Pull request closed without merging**
